[package]
name = "nxr-testkit"
version.workspace = true
edition.workspace = true

[dependencies]
nxr-core = { path = "../nxr-core" }
nxr-security = { path = "../nxr-security" }
nxr-providers = { path = "../nxr-providers" }
nxr-resources = { path = "../nxr-resources" }
nxr-tasks = { path = "../nxr-tasks" }
nxr-observability = { path = "../nxr-observability" }
